### ISSUE TITLE
hello, i would like to add my collection of artistic datasets and models...

### ISSUE THREAD

**Issue by edstoica** [justinpinkney/awesome-pretrained-stylegan3#2]
I would like to share our datasets and models...
--------------------------------------------------------------------------------------------------------------
should i write an issue for each individually, or is it ok like that?
much love,
ed

------------------
- Name: Lucid Layers Stylegan3 Datasets and Models collection
- Source URL (e.g. blog post, tweet etc.): https://github.com/edstoica/lucid_stylegan3_datasets_models/blob/main/README.md
- Resolution: 256-1024
- Config (T or R): T
- Notes (e.g. training details, gamma, FID, kimg, anything else): default, no mirror

_If you'd like to some sample image please attach them to the issue._
![strip_0029 pkl](https://user-images.githubusercontent.com/10214666/152724059-2b8ed872-dad9-44e9-8116-a6f9cb839aeb.jpg)
![strip_0210 pkl](https://user-images.githubusercontent.com/10214666/152724087-a3475488-f503-4d8c-859d-0ec1820f47b5.jpg)
![strip_0162 pkl](https://user-images.githubusercontent.com/10214666/152724108-5fa3cb05-776e-411c-961b-d698ac4222bd.jpg)
![strip_0018 pkl](https://user-images.githubusercontent.com/10214666/152724132-89dc741d-77b4-4eeb-8e33-1f62704aee4a.jpg)
![out](https://user-images.githubusercontent.com/10214666/152724154-45a95234-a043-44b6-92c2-f4a266ae5cda.jpg)
![stri](https://user-images.githubusercontent.com/10214666/152724189-7a03f7e0-b304-4cdd-8611-7dcd184630ea.jpg)
![strip_0236 pkl](https://user-images.githubusercontent.com/10214666/152724209-433f0b2b-8795-4a2c-9470-a284dec937e9.jpg)
![stri](https://user-images.githubusercontent.com/10214666/152724248-8e562118-59e2-4ebf-87a8-7e4e15016aa7.jpg)

**Comment by justinpinkney** [comment]
Fantastic! I'll add them thanks.

**Comment by edstoica** [comment]
thanks justin.
this really gives me new energy, to take the time for updates and adding new datasets and models 👍
