### ISSUE TITLE
 about Landscapes 256     model  

### ISSUE THREAD

**Issue by zhanghongyong123456** [justinpinkney/awesome-pretrained-stylegan3#3]
I've been following your updates and I'd like to ask a few questions about GANs，1.How to train a model with large resolution, I see it is 256x256  2. I want to edit some properties（like rain, snow, forests, mountains, etc.） of the Landscapes，Which project can be used to achieve

Looking forward to your reply, thank you again

**Comment by justinpinkney** [comment]
1. I tried to train a 1024x1024 model but it wouldn't converge after much trying. 
2. You'd have to look into some methods for finding latent directions for the model, either using a supervised method like interfaceGAN or an unsuperivsed on like GANspace
